### ISSUE TITLE
Authorization ? 

### ISSUE THREAD

**Issue by emathias** [TossShinHwa/node-odata#81]
Hi, 

In first place thanks a lot for node-odata. It's really handy and has saved us a lot of time!

I would have a question regarding authorizations. For express, we use acl (https://www.npmjs.com/package/acl) to implement authorizations, in the moment we define routes. 

Considering that node-odata removes the need of manually defining routes, do you have any idea how I could implement authorizations on top of node-odata. 

Any idea is welcome!

Thanks.

**Comment by TossShinHwa** [comment]
Hi @emathias ,

You should use `resources.auth(...)` for authorizations. Here is [document](http://tossshinhwa.github.io/node-odata/en/#51-resource) for this.

It's a synchronize function, so you should cache your authorization when app start.

You can add any Express middleware like [this](https://github.com/TossShinHwa/CMS/blob/master/server/server.coffee#L18), because `node-odata` is based on express, I think the [acl](https://www.npmjs.com/package/acl) will be work well.

Thanks.
